name: bug
description: Fixes a broken user experience
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we see this bug ourselves?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
