name: Chore
description: Docs, tests, formatting, version bumps, or refactoring
title: "chore: "
labels: ["chore"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any specific files, links, or reasons?
    validations:
      required: false
