name: Feature
description: Changes code logic AND affects the end user
title: "feat: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: What is the user facing? Why do we need this?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should the new logic work?
    validations:
      required: true
